# Generated by Django 5.1.2 on 2024-10-27 07:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('ROUTER', 'Router'), ('SWITCH', 'Switch'), ('SERVER', 'Server'), ('FIREWALL', 'Firewall'), ('WORKSTATION', 'Workstation'), ('OTHER', 'Other')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('MAINTENANCE', 'Maintenance'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('snmp_community', models.CharField(blank=True, max_length=100)),
                ('ssh_username', models.CharField(blank=True, max_length=100)),
                ('ssh_password', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
