# Generated by Django 5.1.2 on 2024-11-03 06:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_device_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemresources',
            options={'verbose_name_plural': 'System Resources'},
        ),
        migrations.AddField(
            model_name='systemresources',
            name='bytes_received',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemresources',
            name='bytes_sent',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemresources',
            name='cpu_frequency',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='systemresources',
            name='cpu_usage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='systemresources',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemresources',
            name='disk_usage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='systemresources',
            name='memory_usage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='systemresources',
            name='used_disk_space',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemresources',
            name='used_memory',
            field=models.BigIntegerField(default=0),
        ),
    ]
