# Generated by Django 5.1.2 on 2024-11-03 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_systemresources_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetricsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField(default=0)),
                ('memory_used', models.BigIntegerField(default=0)),
                ('memory_total', models.BigIntegerField(default=0)),
                ('memory_percent', models.FloatField(default=0)),
                ('disk_used', models.BigIntegerField(default=0)),
                ('disk_total', models.BigIntegerField(default=0)),
                ('disk_percent', models.FloatField(default=0)),
                ('network_bytes_sent', models.BigIntegerField(default=0)),
                ('network_bytes_recv', models.BigIntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_history', to='inventory.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
    ]
